kenichi-asai/ocaml-blockly

- blocks/typed_blocks.js
- generators/typedlang.js
- generators/typedlang/blocks.js
`@` ブロックを追加しました。
左のメニューからは現れないので、block_of_ocaml を書き足さない限り使えません。
> リスト結合演算子ブロックを追加

- blocks/datatypes.js
- blocks/typed_blocks.js
- msg/json/ja.json
- msg/messages.js
ツールチップを変更しました.
　・変数とmatch文
　　- let_typed : 「変数の定義」
　　- let_rec : 「再帰関数の定義」
　・組とレコード定義
- defined_record_typed : 「レコードを定義」
　・リスト
　　- list_empty_typed : 「長さ0でデータ、レコードを含まない空のリストを返す」
　　- list_cons_typed : 「追加・削除、またはセッションの順序変更して、このリストブロックを再構成する」
　・進んだ構文
　　- pair_first_typed : 「ペアの一つ目を取得する」
　　- pair_second_typed : 「ペアの二つ目を取得する」
> Changed list,pair,record,let tooltipss

- blocks/typed_blocks.js
- generators/typedlang/blocks.js
統一的な OCaml => block 変換のために、 `List.map` `List.filter` `List.assoc` `List.append`（ `@`） `List.fold_left` `List.fold_right` `List.fold_left2` 内の `<value>` の名前を変えました。
ブロックの全ての穴を埋められて問題なく block => OCaml 変換ができることを簡単に確認しました。
> List モジュール関数ブロックの field 名を統一

- demos/universe/dev.html
- demos/universe/typed.js
universe/dev.html に Save ボタンと Load ボタンとその機能を追加しました。
`Save`：押すと `game.ml` というファイルがダウンロードされる。ファイルの中身はワークスペースのブロックを ml に変換したもの。
`ファイルを選択`：クリックするとファイルダイアログが出て（ `.ml` しか選べない）、ファイルを選ぶとボタンの右にファイル名が出る。Finder などからファイルをドラッグしててきも良い。
`Load`：押すと右の `ファイルを選択` にあるファイルをブロックに変換して、ワークスペースに追加する。
スタイルは最低限です。
Save を押したらファイルダイアログが出てほしかったですが、無理な感じがしたので諦めました。
> 【Universe】Save・Load 機能を追加

- demos/universe/dev.html
- demos/universe/style.css
- demos/universe/typed.js
大きめのゲームを作りたかったので、押すとワークスペースと右の部分の境界線が移動するボタンを作りました。
ゲームが表示されるエリアの場所は変えていないので、縦に大きいゲームは表示しきれません。
私が使いたいだけなので、あまり良くなければ採用しないでいただいてかまいません。
> 右のエリアを広げるボタンを追加

- demos/universe/dev.html
- demos/universe/style.css
Saveボタンの後とLoadボタンのうしろに改行を入れました。
変更前の画像
Save・Load ボタン追加と右のエリアの拡張を並行して別のブランチで行った結果、右のエリアを拡張したときにボタンが４つ横並びになってしまったのが気持ち悪かったので、改行を入れました。
改行を入れるとファイル選択と Load の関係が分かりにくくなったので、色付きの箱に入れました。
変更後の画像
> Save・Load ボタンの後に改行

- blocks/datatypes.js
- msg/messages.js
型ブロックと型定義ブロックの色が同じになってしまっていたので、
カラーラベルを1つ追加し、区別させました。
> distinguish type block's color and define type block's color

- blocks/typed_blocks.js
- demos/universe/dev.html
- generators/typedlang/blocks.js
- msg/messages.js
`Random.int` ブロックと `Random.float` ブロックを足しました。
Universe のみ、ツールボックス？（左の部分）の「進んだ構文」の最後に追加しました。
基本的に `Random.int` は `abs` 、 `Random.float` は `sqrt` をコピーして作りました。
`Random.bool` も足そうと思っていたのですが、引数が `()` なので今回は諦めました。
> Random.int と Random.float ブロックを追加

- demos/typed/typed.js
Run ボタンを複数回押すとどこまでが一回の実行の結果なのかが分かりにくいので、毎回の実行結果の下に水平線を追加しました。
Clear を押すと水平線も消えます。
> 実行結果の最後に水平線を追加

- blocks/typed_blocks.js
- generators/typedlang/blocks.js
block-of-ocaml で List モジュールなどと統一的に処理するために、 `Random.int` と `Random.float` 内で使われている変数の名前を変更しました。
変更後にこれらのブロックが使えてコードへの変換もできたことを確認した時の画像です。
> Random.int と Random.float 内部の変数名を変更

- core/rendered_type_expr.js
> Color.t 型のコネクタの形を定義

- demos/universe/dev.html
ゲームを作るのに `float_of_int` などを使いたいので、メニューに追加しました。
追加したもの
`int_of_float` `float_of_int` `string_of_float` `string_of_bool`
追加しなかったもの（実行時エラーが怖いので）
`int_of_string` `bool_of_string`
そもそもブロックが無かったもの
`float_of_string`
> (universe) float_of_int ブロックなどをメニューに追加

- demos/universe/dev.html
- demos/universe/style.css
- demos/universe/typed.js
Save ボタンの上にファイル名を入力する欄を作って、そこに入力されたファイル名で保存するようにしました。
ゲームを作る上で何度もバックアップをしておきたくなったのですが、全部同じファイル名（game.ml）だとそれぞれどこまで書き進めた状態のファイルなのかが分かりにくいので、ファイル名を好きに変えたいと思いました。
- `input` 要素を追加
- 初期値は `game`.ml
- `Save` ボタンに関する入力だと分かるように、色付きの同じ箱に入れた
- `Save` 時に、ファイル名を `input` 要素から取得するように変更
- `Load` 時に、`input` 要素のファイル名をロードするファイルの名前に書き換えるようにした
- それにあたってファイル名から `.ml` を取り除く必要があったため、 `.ml` 以外のファイルはアップロードできないようになった
> (universe) 保存するファイル名を入力するように変更

- generators/typedlang/blocks.js
- msg/messages.js
`int_of_float` `float_of_int` `string_of_bool` がコードに変換できなかったので足しました。
ついでに `int_of_float` の tooltip の値が未定義だったので足しました。
> generator に int_of_float などを追加

- blocks/typed_blocks.js
- generators/typedlang/blocks.js
`int_of_float` 等を block-of-ocaml で統一的に処理するため、引数の要素の名前を変えました。
> block_of_ocaml のために Value の名前を変更

- blocks/datatypes.js
画像の `true` ブロックを付けようとしたらエラーになってしまったので、付けられるように直しました。
> [] と None パターンブロックの修正

- blocks/datatypes.js
以下のプログラムの `let margin =` 以降のブロックをゴミ箱にドラッグしたらエラーになったので、そこでエラーにならないように書き換えました。（こういった関数は本当に必要なのでしょうか…）
```
let width = 300
let height = 300
let length = 100
type world_t = {
cells : ((int * int) * bool option) list;
player : bool;
}
let rec create_initial_cells x y =
if y > 3 then []
else (if x > 3 then create_initial_cells 1 (y + 1)
else ((x, y), None) :: create_initial_cells (x + 1) y)
let initial_world = {cells = create_initial_cells 1 1; player = true}
let margin = 10
let shape_size = length + margin + margin
let line_size = 10
let line_size2 = (line_size * 5) / 7
let background = place_images [line [(0, height)] Color.black; line [(0, height)] Color.black; line [(width, 0)] Color.black; line [(width, 0)] Color.black] [(length, 0); (length * 2, 0); (0, length); (0, length * 2)] …
```
> [] と None ブロックの修正

- demos/universe/typed.js
ファイルを選択していない状態で `Load` を押したらファイルダイアログが出るように変更しました。
ファイルを選択していない状態で `Load` を押すと「ファイルを選択してください。」という alert が出ていたが、それを消し、ファイルを選択し、もう一度 `Load` を押すのは手間がかかる。
`Load` を押したらすぐにファイルを選べるようにしたい。
- `Load` ボタンクリック時の、ファイルが選択されていない場合の動作を変更
- 「ファイルを選択してください」アラートが出るのをやめた
- 最初に「ファイルを選択」要素を押した時の動作（ファイルダイアログが出る）をするようにした
- ~その後 0.5 秒ごとにファイル選択が完了したかどうかを判定し、選択されていたらもう一度 `Load` ボタンの関数を実行することで、ただちにブロックに変換されるようにした~
修正して解決しました。
- ~ファイルを選択されていない状態で `Load` を押すと 0.5 秒ごとのループが始まり、ファイルが選択された時点でループは停止するが、もしそのままファイルを選択せずに新しくブロックを組み始めたりすると、無駄に無限ループが動き続ける。~
- ~あまりそんな人はいないかもしれないし Run Game を２回以上押すことよりは軽いと思うので無視してもいいかもしれない~
> Load を押した時にファイルを開くダイアログが出るように

- blocks/typed_blocks.js
- demos/universe/dev.html
- demos/universe/typed.js
- generators/typedlang/blocks.js
`place_image` と同じことを `scene_t` の代わりに `Image.t` でできる `overlay` 関数ブロックを追加しました。
[問題点](#problem) があるので、修正したほうが良ければコメントをいただきたいです。
画像を組み合わせたものをさらに `place_image` の第１引数として他の画像に乗せたいことがあるが、 `place_image` の第１引数は `scene_t` 型なのでそういうことはできなかった。
`place_image : Image.t -> (int * int) -> scene_t -> scene_t` と同じことをする、
`overlay : Image.t -> (int * int) -> Image.t -> Image.t` という扱いのブロックが欲しい。
- `overlay` ブロックを追加
- generator に `overlay` ブロックを追加
- `demos/universe/dev.html` に `overlay` ブロックを追加
- `Run` / `Run Game` 時のヘッダ(?)に `let overlay = place_image` を追加
- `circle` ブロックの generator に間違いがあったので修正
<a name="problem"></a>
実行時 `open` 文の直後に `let overlay = place_image` という文を足したため、 `Run` の結果が常に
```
val overlay :
UniverseJs.Image.t -> int * int -> UniverseJs.Image.t -> UniverseJs.Image.t =
<fun>
```
で始まってしまう。
これがまずいようなら、 …
> Added overlay block

- generators/typedlang/blocks.js
`big_bang` を OCaml に変換するときに、 `;; big_bang` とされるようにしました。
> big_bang ブロックから生成される文字列を変更

- blocks/typed_blocks.js
- generators/typedlang/blocks.js
block_of_ocaml を簡潔に書くために、 `&&` / `||` ブロックの引数の名前を `A`, `B`, `C2`, `C3`, ... から `PARAM0`, `PARAM1`, `PARAM2`,  ... に変更しました。
軽い動作確認をしました。
これが merge されたのを確認したら block_of_ocaml を変更します。
> && と || の value 名を PARAMn に変更

- core/blockly.js
- core/ui_events.js
- core/workspace.js
undoをWorkspaceを跨いでできるようになりました。
- groupid が ""のものは、globalUndoStackに入らないようになっているので、今の所 Events.UiWithUndoは globalUndoStack には入っていません。
> globalundostack改良

- core/blockly.js
- core/events.js
ハイライト機能で上下左右移動できるようになりました。
関数名だけどうすればいいかわからず、とりあえずの名前をつけました。
あと、shiftキーの操作の仕方を教えていただいてできるようになったので、ブロックの対応キーを少し変更しました。
●shift + 0 — 実数
●0 — 整数
●i  —  if
●a — abs
●s — sqrt
●shift + ;— +
●. — +.
●shift + 2 — 文字列
●shift + c — 文字列の結合
●b(boolean) — true,falseブロック
●n — not
●shift + 6 — &&, || ブロック
●- — =
●shift + l — let (inのあるやつ)
●l  — let (これはハイライトがなくても使えます。)
●m  —  match
●t — type
●p — pair ( , )
●shift + [  — 空リスト
●[ — 空じゃないリスト
●: — cons（リスト）
> highlight機能改良
