blocks/typed_blocks.js, msg/json/ja.json, msg/messages.js
=> 多言語化 add/remove in

blocks/typed_blocks.js, msg/json/ja.json, msg/messages.js
ブロックの追加
- float_of_int ブロックをtyped_block.jsに追加
=> Add float_of_int block

blocks/typed_blocks.js, demos/typed/dev.html, msg/json/ja.json, msg/messages.js
=> string of float

blocks/typed_blocks.js, msg/json/ja.json, msg/messages.js
ブロックの追加
- string_of_bool
- bool_of_string
=> Add 2 blocks

blocks/typed_blocks.js, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
=> add List.assoc

generators/typedlang/blocks.js
String of floatのBlock->Ocaml部分を追加しました。
=> String of floatのBlock->Ocaml部分追加

blocks/typed_blocks.js, demos/typed/dev.html, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
コンフリクトしてしまったList.filter をやり直しました
=> List filter 

blocks/typed_blocks.js, generators/typedlang/blocks.js
=> Add List.fold_left block

blocks/typed_blocks.js, demos/typed/dev.html, demos/universe/dev.html, generators/typedlang/blocks.js
=> List.fold_right

blocks/typed_blocks.js, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
place_image ブロックを作りました.
- ツールチップは、
　「元の画像の上に新たな画像を指定した位置に重ねる」にしました.
- ブロック → OCaml も変更しました.
- 色はread_imageと同じです.
=> Add place_image block

blocks/typed_blocks.js, demos/universe/dev.html, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
places_images のブロックを追加しました。
　- ツールチップ追加
　- Block → OCaml も追加
　- 色もread_image, place_image と同じです
=> Add places_image block

blocks/typed_blocks.js, demos/universe/dev.html, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
ormap のブロックの追加
- ツールチップ追加
- Block → OCaml 追加
- dev.html の 進んだ構文に追加
- 色はread_image, place_image, place_imagesと同じ
place_image と place_images の 空白部分も消した
=> Add ormap block

blocks/typed_blocks.js, demos/universe/dev.html, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
=> Add polygon block

blocks/typed_blocks.js, demos/typed/dev.html, demos/universe/dev.html, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
circle_outlineブロックを作りました。
ツールチップの名前も直して、demoで試したので大丈夫だと思います。
=> Circle outline

blocks/typed_blocks.js, demos/universe/dev.html, generators/typedlang/blocks.js
color block を追加しました。
基本的な色8色を選択できるようにしました。
=> Add color block

generators/typedlang/blocks.js
=> modify color block generator

blocks/typed_blocks.js, demos/universe/dev.html, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
rgbのみが引数のmake_colorと、
rgbと透過率aが引数のmake_color2
のブロックを追加しました。
=> Add make_color blocks

blocks/typed_blocks.js, demos/universe/dev.html, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
=> empty_scene_blockの追加

blocks/typed_blocks.js, demos/universe/dev.html, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
=> Add line block

blocks/typed_blocks.js, demos/universe/dev.html, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
遅ればせながらrectangle blockを追加しました。
手元のリポジトリを更新する前にしてしまったので、前のempty_sceneの変更が反映されていません。
=> rectangle_blockの追加

demos/universe/dev.html
左のメニューの分類を変更してみました。
Universeのブロックのところ、名前は迷っている状態です。
=> メニューの分類を変更した

blocks/typed_blocks.js
rectangle block の color 設定を color ラベルを使った表記に変えました。
=> Rectangle block's color

blocks/datatypes.js, blocks/typed_blocks.js
type文の定義から生成されるレコードブロックと
let文から生成される変数ブロックの色を色ラベルに対応させました。
=> Variable and record block color

demos/universe/dev.html, demos/universe/style.css, demos/universe/typed.js
=> Clear ボタンと toplevel の水平線を universe にも追加

core/rendered_type_expr.js
Color.t はどんな形にすることになっているか忘れてしまったので今度やります。
=> Image.t と Scene.t のコネクタの形を定義

demos/universe/typed.js
コードをブロックに変換するとき、
コードが変わってもブロックに反映されないバグありましたので直しました。
=> ブロック変換時のバグ

blocks/typed_blocks.js, demos/typed/dev.html, demos/universe/dev.html, generators/typedlang/blocks.js, msg/messages.js
=> List.partition ブロックを追加

demos/universe/dev.html, msg/messages.js
option 型の　block の色を変更しました。
その他、並びを少々変更しました。
=> option 型の　block の色を変更

blocks/typed_blocks.js, demos/universe/dev.html, generators/typedlang/blocks.js
List.fold_right2を追加しました。
List.fold_rightやList.fold_leftなどにツールチップがなかったので、それに合わせてツールチップをつけてません。
=> List.fold_right2を追加

blocks/typed_blocks.js, generators/typedlang/blocks.js
make_color2 の引数のところの名前を、block-of-ocaml のために変えました。
=> make_color2 の Value の名前を変更

demos/universe/typed.js
とても今更ですが、ゲーム部分で矢印キーを押したときにスクロールしないようにしました。
=> 右の部分で矢印キー無効化

demos/universe/seminar.html, demos/universe/typed.js
用意されたプログラムを読み込むために、あるURLにあるファイルを読み込んでブロックに変換するボタンを追加しました。
先生のセミナー用プログラムを使おうとしたのですが、認証が必要で面倒だったので私が公開したテスト用プログラムを読み込むようにしてあります。
=> 特定のURL(仮)のプログラムを読み込むボタンを追加

core/mutator.js
=> Big bang block

demos/universe/book.html, demos/universe/example.html, demos/universe/seminar.html, demos/universe/typed.js
=> 新しいタブで実行する

demos/la10a/la10test.html, demos/la10a/src/test.ml
第10章のゲームに終了条件を追加し、htmlの文章を変更しました。
ご確認よろしくお願いします。
=> 第10章 終了条件追加・html変更

blocks/typed_blocks.js, generators/typedlang/blocks.js, msg/json/ja.json, msg/messages.js
- `List.for_all2` の ブロックを作りました。
- Block => OCaml も対応しています。
-  ツールチップも加えました。（ツールチップはこれで大丈夫ですか。）
=> List.for_all2 ブロックの追加

demos/la10a/la10-1.html, demos/la10a/la10-2.html, demos/la10a/la10-3.html, demos/la10a/la10-4.html, demos/la10a/la10test.html, demos/la10a/src/la10-1-ans.ml, demos/la10a/src/la10-1.ml, demos/la10a/src/la10-2.ml, demos/la10a/src/la10-3-1.ml, demos/la10a/src/la10-3-2.ml, demos/la10a/src/la10-3-ans.ml, demos/la10a/src/la10-3-ans2.ml, demos/la10a/src/la10-4-ans.ml, demos/la10a/src/la10-4.ml, demos/la10a/src/test.ml
第10回のhtmlと.mlファイルを作成しました。
結構章を分ける段階を大雑把にした感じがあるので変更点が上がり次第編集します。
=> 第10回のhtmlと.mlファイル作成

demos/linear_function/5_heniki/index.html
dev.htmlではなくdev-new.htmlが正しいリンク先と思われるため、変更しました
=> Fix link destination
